version: '3.4'

services:
  jobslisting:
    image: jobslisting
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 3000:3000
    volumes:
      - ./uploads:/usr/src/app/uploads
    depends_on:
      - db

  redis:
    image: redis:7
    volumes:
      - redis-data:/data

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: Jobs
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  redis-data:
